### ISSUE TITLE
Code seems to work on inverter with SN 603xxx

### ISSUE THREAD

**Issue by marcovansteen** [Woutrrr/Omnik-Data-Logger#10]
I noticed that the python script reads out my inverter correctly.
So maybe README.MD can be updated so people with 603 are not discouraged to try.

Inverter: NLDN2020134J1085
S/N: 603701905
FW Main: NL1_V1.0-0043-4
FW Slave: V1.6-0018

**Comment by Woutrrr** [comment]
Updated the readme with supported s/n
