### ISSUE TITLE
Solution for S/N 601 wifi kits

### ISSUE THREAD

**Issue by wouterbaake** [Woutrrr/Omnik-Data-Logger#16]
I've got a wifi card in my Omnik 3k-TL that has a 601 serial number and is not supported by this script. I've made a "packet sniffer" version of this script (with MQTT support and without the MySQL support) that is available at https://github.com/wouterbaake/OmnikMQTT.

**Comment by Woutrrr** [comment]
I've updated the readme with a reference to your project.upported inverters
