### ISSUE TITLE
LiveStats.py doesn't work

### ISSUE THREAD

**Issue by molekuul** [Woutrrr/Omnik-Data-Logger#20]
There are 4 issues with the LiveStats.py:
1. there is a missing entry in the config.cfg, log_enabled
2. the logfilename entry in the config.cfg should be log_filename in stead of filename
3. line 66: print "ID: {0}".format(msg.id()) should be print "ID: {0}".format(msg.id)
4. line 86: format(msg.id(),  should be format(msg.id,

**Comment by Woutrrr** [comment]
I made changes to the main script which broke the LiveStats.py script. I've updated the LiveStats to fix the errors and it should work again.

Can you try the latest version ?

**Comment by molekuul** [comment]
Hi Wouter,

yes it does work now.

thanks,

kind regards,

Joris Weijters


Wouter van der Zwan schreef op 2015-12-23 22:16:
