### ISSUE TITLE
Question about serie number

### ISSUE THREAD

**Issue by lodesmets** [Woutrrr/Omnik-Data-Logger#41]
Hey, I see you posted that your script works with modules from 602xxxxxx to 606xxxxxx.
But those codes are 9 digits long, and my module has a code 1603xxxxxx.
Do I need to remove the first 1, or does the code not work for my module

**Comment by sincze** [comment]
Mine is ('InverterSN',1602*****8) and is working ;-)

**Comment by lodesmets** [comment]
> Mine is ('InverterSN',1602*****8) and is working ;-)

What firmaware are you on?

**Comment by lodesmets** [comment]
Nevermind, I made a typo in the serienumber
